version: "3.3"
services:
  proxy:
    container_name: c_proxy
    image: joshix/caddy:v1.0.5
    restart: on-failure:5
    command: -agree
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    cap_add:
     - CAP_NET_BIND_SERVICE
    ports:
     - 80:80
     - 443:443
    volumes:
     - ../files/save/caddy:/.caddy:rw
     - ../files/config/caddy:/var/www/html:ro
    networks:
     - vsa

  meteor:
    container_name: c_meteor_1
    image: abernix/meteord:node-12-base
    restart: on-failure:5
    ports:
     - "127.0.0.1:3000:80"
    links:
     - mongo
    volumes:
     - ../backup:/backup
     - data-volume:/data
     - ../build/bundle:/built_app
    environment:
     - ROOT_URL=https://www.vertexshaderart.com
     - IMAGE_PATH=/data/images
     - METEOR_ALLOW_SUPERUSER=true
     - MONGO_URL=mongodb://mongo:27017/admin
    env_file:
     - ../files/config/meteor/settings.env
    networks:
     - vsa

  mongo:
    container_name: c_mongo_1
    image: mongo:4.2.7-bionic
    restart: on-failure:5
    ports:
     - "127.0.0.1:27017:27017"
    volumes:
     - ../backup:/backup
     - data-volume:/data
    networks:
     - vsa

networks:
  vsa:
    driver: bridge

volumes:
  data-volume:

